[pytest]

filterwarnings =
    ignore::UserWarning

addopts = --verbose --tb=short --disable-warnings  --gherkin-terminal-reporter --show-capture=no
          --allure-link-pattern="issue:https://code.waters.com/jira/browse/{}"
          --alluredir=results/allure-results
log_cli = false
log_file = ./results/pytest.log
log_file_level = DEBUG
log_file_format = %(asctime)s - %(levelname)s - %(name)s - %(message)s


testpaths = tests/ICS/step_defs
            tests/ISYM/step_defs
            tests/kiosk/API/step_defs
            tests/kiosk/UI/step_defs
            tests/method_editor/step_defs
            tests/system_tests/step_defs

norecursedirs = .git .github .piper .vscode config devops-config docker isym_test_api scripts utilities web_framework tests/method_editor/features tests/system_tests/features tests/kiosk/API/features tests/kiosk/UI/features tests/ICS/features

markers =
    smoke
    columnApi
    rotary
    api
    wavelength
    command
    columnTemperature
    ui
    signIn
    tuvConfiguration
    column
    dashboard
    system
    prime_solvent
    seal
    ColumnApi
    flow
    samplePressureConditionCard
    reg
    flowConditionCard
    systemPressureConditionCard
    plots
    sampleManager
    tuvConfiguration
    user
    solventCompositionConditionCard
    channelLampOff
    channelLampOn
    solventManagerConfiguration
    roomTemperature
    sampleTemperature
    valvePositionConditionCard
    flowPathConditionCard
    pickerComponent
    userProfile
    kioskUserSettings
    userSub
    deltaPressureConditionCard
    flows
    maintainScreen
    instrumentConfiguration
    leakTest
    startupWorkflow
    ambientTemperature
    reg
    solventCompositionFieldFocus
    mobilePhaseSolvents
    columnManagerConfiguration
    calibrateWavelengthWorkflow
    calibrateAxesWorkflow
    primeSolventWorkflow
    mobilePhase
    flowHintMessages
    solventCompositionFieldFocus
    DynamicLeakTest
    needleSealReadinessWorkflow
    schematic
    MANUAL
    hintMessages
    reg11
    injectionCountConditionCard
    heaterCoolerWorkflow
    workFlow
    workFlow
    sampleMeteringPumpWorkflow
    noiseDriftWorkflow
    solventCompositionFieldFocus
    ui1
    FCS
    SystemLeakTest
    sampleTemperatureTestWorkflow
    volumnPumped
    flowCellConditionCard
    uvLampConditionCard
    replaceNeedle
    pumpMaintenanceWorkFlow
    replaceColumnWorkflow
    replaceFlowCellWorkflow
    replaceSealWorkflow
    Shutdownflow
    pumpModuleConfiguration
    autosampler
    systemLogs
    ShutdownWorkflow
    pumpMaintenanceWorkflow
    prime
    replaceLampWorkflow
    verify
    calibrate
    mobilePhaseAll
    workFlow
