# Path to the Allure root directory (relative or absolute)

# Version of the Allure CLI to use
version=2.25.0
# path to allure-results folder
allureResultsDirectory=results/allure-results
allureReportDirectory=results/allure-report

# URL to download the Allure CLI zip file from
commandLineUrl=https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline

# Maximum number of threads to use when generating reports
threads=4
