@system @ALIST-231 @system_SM-FTN_alarms_feature
Feature: System | SM-FTN Alarms Workflow

  Background:
    Given an instrument system in "IDLE" state is connected

  @real @weekly @new @ignore
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" alarm with "<degrees>" degrees and "<valve_position>" valve position
    Then User confirms the error state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the header
    And User confirms in the log the date is the current date
    And User confirms in log the category is error
    And User confirms in log that the source is SM-FTN
    And User validates the "<issue>" is displayed in issue resolution field
    And User validates the issue resolution is red color

    Examples:
      | alarm_type                        | degrees | valve_position | message                                               | issue                                                 |
      | BetaDriveLost                     | 5       | N/A            | Beta Drive lost synchronization 5.0 degrees           | Beta Drive lost synchronization 5.0 degrees           |
      | BetaDriveMoveExceedsThreshold     | 7       | N/A            | Beta Drive move error 7.0 degrees                     | Beta Drive move error 7.0 degrees                     |
      | BetaMoveFailedAccuracyCriteria    | 8       | N/A            | Beta Drive accuracy failure 8.0 degrees               | Beta Drive accuracy failure 8.0 degrees               |
      | InjectValveMoveFailure            | N/A     | 3              | Inject Valve failed moving to inject position         | Inject Valve failed moving to inject position         |
      | InjectValveMoveThreshold          | 8       | 6              | Inject Valve failed moving to 6 Error:8.0 degrees     | Inject Valve failed moving to 6 Error:8.0 degrees     |
      | MultiDrawValveMoveFailure         | N/A     | 2              | Multi Draw Valve failed moving to 2                   | Multi Draw Valve failed moving to 2                   |
      | MultiDrawValveMoveThreshold       | 5       | 3              | Multi Draw Valve failed moving to 3 Error 5.0 degrees | Multi Draw Valve failed moving to 3 Error 5.0 degrees |
      | InvalidPlateId                    | N/A     | 3              | Plate configuration invalid plate location 3          | Plate configuration invalid plate location 3          |
      | RotaryPlatterEncoderMotorLostSync | 6       | N/A            | Rotary platter lost synchronization:6.0 degrees       | Rotary platter lost synchronization:6.0 degrees       |
      | RotaryPlatterMoveExceedsThreshold | 7       | N/A            | Rotary platter error 7.0 degrees                      | Rotary platter error 7.0 degrees                      |
      | RotaryPlatterMoveAccuracyCriteria | 8       | N/A            | Rotary platter accuracy failure 8.0 degrees           | Rotary platter accuracy failure 8.0 degrees           |
      | SampleHeaterCoolerOverTemperature | 9       | N/A            | Sample heater cooler over temperature 9.0 degC        | Sample heater cooler over temperature 9.0 degC        |
      | SampleHeaterCoolerADCSaturated    | 1       | N/A            | Sample heater saturated 1.0 degC                      | Sample heater saturated 1.0 degC                      |
      | SampleTemperatureFailure          | 4       | N/A            | Sample temperature failure at 4.0 degC                | Sample temperature failure at 4.0 degC                |
      | FinTemperatureFailure             | 90      | N/A            | Sample fin temperature failure at 90.0 degC           | Sample fin temperature failure at 90.0 degC           |
      | SampleTemperatureManagerFailure   | 3       | N/A            | Sample Temperature Manager failure at 3.0 degC        | Sample Temperature Manager failure at 3.0 degC        |


  @real @weekly @new @ignore
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" alarm with "<sample_volume>" sample volume, "<max_volume>" max volume, "<mix_volume>" mix volume and "<sample_pump>" sample pump
    Then User confirms the error state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the header
    And User confirms in the log the date is the current date
    And User confirms in log the category is error
    And User confirms in log that the source is SM-FTN
    And User validates the "<issue>" is displayed in issue resolution field
    And User validates the issue resolution is red color

    Examples:
      | alarm_type                                     | sample_volume | max_volume | mix_volume | sample_pump | message                                                        | issue                                                          |
      | SampleDrawExceedsMaximum                       | 23            | 20         | N/A        | N/A         | Sample 23.0 uL draw exceeds maximum volume of 20.0 uL          | Sample 23.0 uL draw exceeds maximum volume of 20.0 uL          |
      | SampleDrawExceedsSamplePumpMaxVolume           | 13            | 10         | N/A        | N/A         | Sample 13.0 draw exceeds sample pump max volume of 10 uL       | Sample 13.0 draw exceeds sample pump max volume of 10 uL       |
      | SampleDrawPlusMixVolExceedsSamplePumpMaxVolume | 15            | N/A        | 15         | 20          | Sample 15.0 uL draw plus mix 15.0 uL exceeds sample pump 20 uL | Sample 15.0 uL draw plus mix 15.0 uL exceeds sample pump 20 uL |
      | SamplePumpExcessiveDraw                        | N/A           | N/A        | N/A        | 35          | Sample pump 35.0 uL draw request exceeds capacity              | Sample pump 35.0 uL draw request exceeds capacity              |
      | SamplePumpExcessiveDispense                    | N/A           | N/A        | N/A        | 25          | Sample pump 25.0 uL dispense request exceeds capacity          | Sample pump 25.0 uL dispense request exceeds capacity          |
      | WashPumpExcessiveDraw                          | N/A           | N/A        | N/A        | 30          | Wash pump 30.0 uL draw request exceeds capacity                | Wash pump 30.0 uL draw request exceeds capacity                |
      | WashPumpExcessiveDispense                      | N/A           | N/A        | N/A        | 25          | Wash pump 25.0 uL dispense request exceeds capacity            | Wash pump 25.0 uL dispense request exceeds capacity            |

  @real @weekly @new @ignore
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" alarm with "<steps>" steps  "<pressure>" pressure and "<position>" position
    Then User confirms the error state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the header
    And User confirms in the log the date is the current date
    And User confirms in log the category is error
    And User confirms in log that the source is SM-FTN
    And User validates the "<issue>" is displayed in issue resolution field
    And User validates the issue resolution is red color

    Examples:
      | alarm_type                                   | steps | pressure | position | message                                                            | issue                                                              |
      | NeedleMoveErrorExceedsThreshold              | 3     | N/A      | N/A      | Needle lost 3 steps                                                | Needle lost 3 steps                                                |
      | FootMoveErrorExceedsThreshold                | 6     | N/A      | N/A      | Needle foot lost 6 steps                                           | Needle foot lost 6 steps                                           |
      | AspirationDepthOutOfRange                    | N/A   | N/A      | 5        | Needle aspiration depth of 5 mm is out of range                    | Needle aspiration depth of 5 mm is out of range                    |
      | PlateOrVialDetectedOutOfRange                | N/A   | N/A      | 10       | Plate or vial detected at 10.0 mm is out of range                  | Plate or vial detected at 10.0 mm is out of range                  |
      | SamplePressureUnableToReachCompressThreshold | N/A   | 200      | N/A      | Sample pump pressure 200.0 psi unable to reach compress threshold  | Sample pump pressure 200.0 psi unable to reach compress threshold  |
      | ErrorFootTooFar                              | N/A   | N/A      | 7        | Needle foot moved too far 7.0 mm                                   | Needle foot moved too far 7.0 mm                                   |
      | FootIsOutOfCalibrationRange                  | N/A   | N/A      | 8        | Needle foot calibration out of range 8.0 mm                        | Needle foot calibration out of range 8.0 mm                        |
      | HardStopOutOfCalibrationRange                | N/A   | N/A      | 9        | Needle foot wash station hard stop calibration out of range 9.0 mm | Needle foot wash station hard stop calibration out of range 9.0 mm |
      | NeedleTooFar                                 | N/A   | N/A      | 6        | Needle moved too far: 6.0 mm                                       | Needle moved too far: 6.0 mm                                       |
      | NeedleMoveFailure                            | N/A   | N/A      | 3        | Needle move failure: 3.0 mm                                        | Needle move failure: 3.0 mm                                        |
      | NeedleBlocked                                | N/A   | N/A      | 2        | Needle motion blocked: 2.0 mm                                      | Needle motion blocked: 2.0 mm                                      |

  @real @weekly @new @ignore
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" alarm with "<flow_rate>" flow rate  and "<pulses>" pulses
    Then User confirms the error state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the header
    And User confirms in the log the date is the current date
    And User confirms in log the category is error
    And User confirms in log that the source is SM-FTN
    And User validates the "<issue>" is displayed in issue resolution field
    And User validates the issue resolution is red color

    Examples:
      | alarm_type                            | flow_rate | pulses | message                                                          | issue                                                            |
      | SamplePumpInvalidFlowRate             | 130       | N/A    | Sample pump invalid flow rate 130 uL/min                         | Sample pump invalid flow rate 130 uL/min                         |
      | SamplePumpHomeNotFoundWithinThreshold | N/A       | 4      | Sample pump home sensor not found within range - Error: 4 pulses | Sample pump home sensor not found within range - Error: 4 pulses |
      | WashPumpInvalidFlowRate               | 400       | N/A    | Wash pump invalid flow rate 400.0 uL/min                         | Wash pump invalid flow rate 400.0 uL/min                         |
      | WashPumpHomeNotFoundWithinThreshold   | N/A       | 3      | Wash pump home sensor not found within range - Error: 3 pulses   | Wash pump home sensor not found within range - Error: 3 pulses   |

  @real @weekly @new @ignore
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" alarm with "<duration>" duration and  "<actual_duration>" actual duration
    Then User confirms the error state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the header
    And User confirms in the log the date is the current date
    And User confirms in log the category is error
    And User confirms in log that the source is SM-FTN
    And User validates the "<issue>" is displayed in issue resolution field
    And User validates the issue resolution is red color

    Examples:
      | alarm_type                      | duration | actual_duration | message                                                   | issue                                                     |
      | SampleLoadingEstimationExceeded | 3        | 9               | Sample load duration exceeded - Est: 5 sec, Actual: 9 sec | Sample load duration exceeded - Est: 5 sec, Actual: 9 sec |

  @real @weekly @new @ignore
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" alarm
    Then User confirms the error state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the header
    And User confirms in the log the date is the current date
    And User confirms in log the category is error
    And User confirms in log that the source is SM-FTN
    And User validates the "<issue>" is displayed in issue resolution field
    And User validates the issue resolution is red color


    Examples:
      | alarm_type                         | message                                                | issue                                                  |
      | AspirationPumpFailure              | Aspiration pump failure                                | Aspiration pump failure                                |
      | BetaDriveResourceUnavailable       | Beta Drive not available                               | Beta Drive not available                               |
      | BetaDriveMoveFailure               | Beta Drive move timeout                                | Beta Drive move timeout                                |
      | BetaDriveSensorNotFound            | Beta Drive sensor not found                            | Beta Drive sensor not found                            |
      | BetaDriveMotionNotDetected         | Beta Drive motion not detected                         | Beta Drive motion not detected                         |
      | BetaDriveFailToDetectHome          | Beta Drive home failure                                | Beta Drive home failure                                |
      | InjectValveResourceUnavailable     | Inject Valve resource not available                    | Inject Valve resource not available                    |
      | InjectValveNotHomed                | Inject Valve not homed                                 | Inject Valve not homed                                 |
      | InjectValveMotionNotDetected       | Inject Valve motion not detected                       | Inject Valve motion not detected                       |
      | InjectValveIndexSensorNotFound     | Inject Valve index sensor not found                    | Inject Valve index sensor not found                    |
      | MultiDrawValveResourceUnavailable  | Multi Draw Valve resource not available                | Multi Draw Valve resource not available                |
      | MultiDrawValveNotHomed             | Multi Draw Valve not homed                             | Multi Draw Valve not homed                             |
      | MultiDrawValveMotionNotDetected    | Multi Draw Valve motion not detected                   | Multi Draw Valve motion not detected                   |
      | MultiDrawValveIndexSensorNotFound  | Multi Draw Valve index sensor not found                | Multi Draw Valve index sensor not found                |
      | RotaryPlatterLost                  | Rotary platter is lost                                 | Rotary platter is lost                                 |
      | RotaryPlatterNotIdle               | Rotary platter not ready to move                       | Rotary platter not ready to move                       |
      | InvalidStopOfUniformTempMotion     | Invalid stop of uniform cooling motion                 | Invalid stop of uniform cooling motion                 |
      | WashStationHardStopNotCalibrated   | Wash station hard stop not calibrated                  | Wash station hard stop not calibrated                  |
      | NeedleTravelDistanceNotCalibrated  | Needle not calibrated                                  | Needle not calibrated                                  |
      | FootPierceNeedleNotCalibrated      | Needle foot not calibrated                             | Needle foot not calibrated                             |
      | PierceError                        | Plate or vial pierce error                             | Plate or vial pierce error                             |
      | DetectBottomFailure                | Plate or vial bottom detection failure                 | Plate or vial bottom detection failure                 |
      | NeedleControlResourceNotAvailable  | Needle resource not available                          | Needle resource not available                          |
      | NeedleMoveTimeOut                  | Needle move timeout                                    | Needle move timeout                                    |
      | FootMoveTimeOut                    | Needle foot move timeout                               | Needle foot move timeout                               |
      | NeedleHomeEdgeNotDetected          | Needle home edge not detected                          | Needle home edge not detected                          |
      | FootHomeEdgeNotDetected            | Needle foot home edge not detected                     | Needle foot home edge not detected                     |
      | NeedleHomeSensorNotFound           | Needle home sensor not found                           | Needle home sensor not found                           |
      | FootHomeSensorNotFound             | Needle foot home sensor not found                      | Needle foot home sensor not found                      |
      | NeedleHomeSensorFailure            | Needle home sensor failure                             | Needle home sensor failure                             |
      | FootHomeSensorFailure              | Needle foot home sensor failure                        | Needle foot home sensor failure                        |
      | NeedleControlMoveOutOfRange        | Needle or foot move out of range                       | Needle or foot move out of range                       |
      | NeedleControlMoveFailure           | Needle and/or foot move failure                        | Needle and/or foot move failure                        |
      | TopSensorFailure                   | Needle foot did not detect vial/plate                  | Needle foot did not detect vial/plate                  |
      | NeedleEncoderNotConnected          | Needle encoder not connected                           | Needle encoder not connected                           |
      | SuperTopsSensorFailure             | Pierce needle detected an obstruction                  | Pierce needle detected an obstruction                  |
      | InvalidPlateLocation               | Plate configuration invalid sample location            | Plate configuration invalid sample location            |
      | RotaryPlatterResourceUnavailable   | Rotary platter not available                           | Rotary platter not available                           |
      | RotaryPlatterMoveFailure           | Rotary platter move timeout                            | Rotary platter move timeout                            |
      | RotaryPlatterSensorNotFound        | Rotary platter sensor not found                        | Rotary platter sensor not found                        |
      | RotaryPlatterMultipleIndexPulses   | Rotary platter detected multiple index sensors         | Rotary platter detected multiple index sensors         |
      | RotaryPlatterSensorEdgeNotFound    | Rotary platter sensor edge not found                   | Rotary platter sensor edge not found                   |
      | RotaryPlatterIndexNotFound         | Rotary platter index sensor not found                  | Rotary platter index sensor not found                  |
      | RotaryPlatterCalibrationInvalid    | Rotary platter calibration invalid                     | Rotary platter calibration invalid                     |
      | SamplePumpResource                 | Sample pump not available                              | Sample pump not available                              |
      | SamplePumpBadContext               | Sample pump unable to accept command                   | Sample pump unable to accept command                   |
      | SamplePumpTimeOut                  | Sample pump move timeout                               | Sample pump move timeout                               |
      | SamplePumpCouldNotMoveOutOfSensor  | Sample pump could not move out of home sensor          | Sample pump could not move out of home sensor          |
      | SamplePumpHomeSensorNotFound       | Sample pump home sensor not found                      | Sample pump home sensor not found                      |
      | SamplePressureTransducerFailure    | Sample pressure transducer failure                     | Sample pressure transducer failure                     |
      | SampleDoesNotExist                 | Sample list is not set                                 | Sample list is not set                                 |
      | SamplePumpLost                     | Sample pump lost                                       | Sample pump lost                                       |
      | SampleHeaterCoolerDisabled         | Sample heater cooler disabled                          | Sample heater cooler disabled                          |
      | SampleHeaterCoolerWrongState       | Sample heater cooler unable to process request         | Sample heater cooler unable to process request         |
      | SampleHeaterCoolerDoorNotSupported | Sample heater cooler door not supported                | Sample heater cooler door not supported                |
      | SampleHeaterCoolerNotDetected      | Sample heater cooler not detected                      | Sample heater cooler not detected                      |
      | ExhaustFanFailure                  | Exhaust fans failure                                   | Exhaust fans failure                                   |
      | CompartmentFanFailure              | Sample compartment fans failure                        | Sample compartment fans failure                        |
      | SampleTemperatureProcess           | Sample Temperature Process failure                     | Sample Temperature Process failure                     |
      | WashPumpResource                   | Wash pump not available                                | Wash pump not available                                |
      | WashPumpBadContext                 | Wash pump unable to accept command                     | Wash pump unable to accept command                     |
      | WashPumpTimeOut                    | Wash pump move timeout                                 | Wash pump move timeout                                 |
      | WashPumpCouldNotMoveOutOfSensor    | Wash pump could not move out of home sensor            | Wash pump could not move out of home sensor            |
      | WashPumpHomeSensorNotFound         | Wash pump home sensor not found                        | Wash pump home sensor not found                        |
      | WashPumpLost                       | Wash pump is lost                                      | Wash pump is lost                                      |
      | SolenoidPathValveFailure           | Wash solenoid valve failure                            | Wash solenoid valve failure                            |
      | NeedleControlStateInvalid          | Needle control in invalid state                        | Needle control in invalid state                        |
      | MapControlLost                     | Needle horizontal position control lost                | Needle horizontal position control lost                |
      | MapControlInvalid                  | Needle horizontal position in invalid state            | Needle horizontal position in invalid state            |
      | InstrumentNotCalibrated            | Instrument not calibrated                              | Instrument not calibrated                              |
      | NeedleControlStateInconsistent     | Needle horizontal control state inconsistent           | Needle horizontal control state inconsistent           |
      | NotEnoughDrawSlots                 | Not enough draw slots                                  | Not enough draw slots                                  |
      | MultiDrawCalculationFailure        | Multi-draw calculations failure                        | Multi-draw calculations failure                        |
      | ErrorNotAtWash                     | Needle not in wash station                             | Needle not in wash station                             |
      | ErrorAspPumpNotRunning             | Aspiration pump is not on                              | Aspiration pump is not on                              |
      | ErrorInjectValveNotInject          | Inject valve is not in the inject position             | Inject valve is not in the inject position             |
      | InjectValve                        | Inject valve failure                                   | Inject valve failure                                   |
      | NeedleBehaviors                    | Needle failure                                         | Needle failure                                         |
      | RotaryPlatter                      | Rotary platter failure                                 | Rotary platter failure                                 |
      | BetaDrive                          | Beta drive failure                                     | Beta drive failure                                     |
      | MapControl                         | Needle horizontal control failure                      | Needle horizontal control failure                      |
      | NeedleWashPump                     | Needle wash pump failure                               | Needle wash pump failure                               |
      | SampleMeteringPump                 | Sample pump failure                                    | Sample pump failure                                    |
      | WashControl                        | Wash pump control failure                              | Wash pump control failure                              |
      | SealWashPump                       | Seal wash pump failure                                 | Seal wash pump failure                                 |
      | SampleDynamics                     | Sample management control failure                      | Sample management control failure                      |
      | RotaryPlatterNoLocked              | Rotary platter not locked                              | Rotary platter not locked                              |
      | ThetaBetaMoveError                 | Needle horizontal control failure                      | Needle horizontal control failure                      |
      | CalibrationPointNotFound           | Advance calibration point not found                    | Advance calibration point not found                    |
      | ReadingRotaryPlatterEncoder        | Error reading rotary platter encoder                   | Error reading rotary platter encoder                   |
      | ReadingBetaDriveEncoder            | Error reading beta drive encoder                       | Error reading beta drive encoder                       |
      | BarcodeHeaterFailure               | Barcode heater failure                                 | Barcode heater failure                                 |
      | BarcodeHeaterOverTemperature       | Barcode heater overtemp condition                      | Barcode heater overtemp condition                      |
      | NotReadyToInject                   | Inject start came before sample is ready for injection | Inject start came before sample is ready for injection |
