@system @ALIST-231 @system_tuv_alarms_feature
Feature: System | TUV Alarms Workflow

  Background:
    Given the "ics_atom_project" project is available in Empower
    And run samples application is open for the current project and system
    And Control Panel shows "IDLE" state

  @real @tuv @weekly
  Scenario Outline: to test the instrument alarm generated by the instrument(s) FW passed through iSym
    When User generates an "<alarm_type>" TUV alarm
    Then Control Panel shows "ERROR" state
    And User validates the "<message>" is displayed in Empower Message Center
    When User opens kiosk app
    Then User confirms the error state in the dashboard
    When User navigates to the system logs screen
    Then log entries have one with current date, "Error" category and "Tuv" source details
    When User navigates from log screen back to dashboard
    And User navigates to issue resolution screen
    Then User validates the "<issue>" is displayed in issue resolution field
    And User validates the top issue resolution is red color

    Examples:
      | alarm_type                           | message                                                  | issue                                                    |
      | LampFailedToTurnOff                  | Failed to turn OFF Lamp                                  | Lamp failed to power-off                                 |
      | LampOffUnexpectedly                  | Lamp turned OFF unexpectedly                             | Lamp turned OFF unexpectedly                             |
      | LampMemoryNotConnected               | External memory lamp device not accessible               | External memory lamp device not accessible               |
      | LampLowIntensity                     | Not enough intensity                                     | Not enough intensity                                     |
      | LampLifeTimeHoursExceeded            | Lifetime lamp hours exceeded                             | Lifetime lamp hours exceeded                             |
      | GratingHomeFailed                    | Grating home failed                                      | Grating home failed                                      |
      | SetWavelength                        | Cannot move the grating to set wavelength                | Cannot move the grating to set wavelength                |
      | WavelengthNotCalibrated              | Wavelength not calibrated                                | Wavelength not calibrated                                |
      | WavelengthCalibrationFailed          | Failed to calibrate wavelength                           | Failed to calibrate wavelength                           |
      | WavelengthVerificationFailed         | Failed to verify wavelength calibration                  | Failed to verify wavelength calibration                  |
      | PeakNotFound_257                     | Failed to find 257 nm peak                               | Failed to find 257 nm peak                               |
      | Erbium257OutOfNominalRange           | Erbium 257 nm out of nominal range                       | Erbium 257 nm out of nominal range                       |
      | PeakNotFound_379                     | Failed to find 379 nm peak                               | Failed to find 379 nm peak                               |
      | Erbium379OutOfNominalRange           | Erbium 379 nm out of nominal range                       | Erbium 379 nm out of nominal range                       |
      | PeakNotFound_521                     | Failed to find 521 nm peak                               | Failed to find 521 nm peak                               |
      | Erbium521OutOfNominalRange           | Erbium 521 nm out of nominal range                       | Erbium 521 nm out of nominal range                       |
      | PeakNotFound_656                     | Failed to find 656 nm peak                               | Failed to find 656 nm peak                               |
      | OpticalFilterReferenceEnergyNotFound | Reference energy could not be established                | Reference energy could not be established                |
      | OpticalFilterEdgeNotFound            | Filter edge not found                                    | Filter edge not found                                    |
      | OpticalFilterShutterSpotNotFound     | Shutter position not found                               | Shutter position not found                               |
      | OpticalFilterErbiumPositionNotFound  | Erbium filter position not found                         | Erbium filter position not found                         |
      | OpticalFilterOrderPositionNotFound   | Order filter position not found                          | Order filter position not found                          |
      | OpticalFilterMoveToSpotFailed        | Move to optical filter spot failed                       | Move to optical filter spot failed                       |
      | InitializeAcquisitionSystem          | Unable to initialize acquisition subsystem               | Unable to initialize acquisition subsystem               |
      | SetDataRate                          | Unable to set use enabled data rate                      | Unable to set use enabled data rate                      |
      | BadAcquisitionSystemState            | Unable to start acquisition due to bad acquisition state | Unable to start acquisition due to bad acquisition state |
      | DataAcquisitionFailed                | Unable to get data from the hardware                     | Unable to get data from the hardware                     |
      | DataRetrieving                       | Data not passed to data subsystem                        | Data not passed to data subsystem                        |
      | DataProcessingSettings               | Unable to set data processing behavior                   | Unable to set data processing behavior                   |
      | FilterParamSettings                  | Unable to set filter parameters                          | Unable to set filter parameters                          |
      | AutoZeroParamSettings                | Unable to set autozero parameters                        | Unable to set autozero parameters                        |
      | AutoZeroBehaviorSettings             | Unable to set autozero behavior                          | Unable to set autozero behavior                          |
      | FlowCellTransmittanceBelowThreshold  | FlowCell Transmittance Below Threshold                   | FlowCell Transmittance Below Threshold                   |
      | BadSystemState                       | Bad grating state                                        | Bad grating state                                        |
      | ConfigureADC                         | Error configuring ADC                                    | Error configuring ADC                                    |
      | InvalidFlowCell                      | Invalid flow cell                                        | Invalid flow cell                                        |
      | DarkCurrentHigh                      | Error when Dark Current measurement is too high          | Error when Dark Current measurement is too high          |
      | LampOverTemp                         | Lamp over temperature detected                           | Lamp over temperature detected                           |
      | NotReadyToStartAcquisition           | Acquisition start trigger was not received               | Acquisition start trigger was not received               |